spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/ems
        username: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

        springdoc:
            swagger-ui:
                path=/custom/swagger-ui:
